services:
  starknet-devnet:
    image: shardlabs/starknet-devnet-rs:latest-seed0
    container_name: starknet-devnet
    ports:
      - "5050:5050"
    networks:
      - starknet-network
    healthcheck:
      test: ["CMD", "starknet-devnet", "--version"]
      interval: 5s
      timeout: 5s
      retries: 5
  deployer:
    image: deploy
    container_name: deployer
    volumes:
      - .:/app  # Mounts the current directory into /app in the container
    env_file:
      - .env.local
    # environment:
    #   - ENV_VAR=value  # Example environment variable
    ports:
      - "8080:8080"  # Example port mapping
    networks:
      - starknet-network
    stdin_open: true   # Keeps container interactive
    tty: true          # Allocate a pseudo-TTY (good for bash/shell access)
    depends_on:
      starknet-devnet:
        condition: service_healthy
    command: [ "sh", "-c", "chmod +x scripts/deploy-mock-hash-storage.sh && ./scripts/deploy-mock-hash-storage.sh" ]
networks:
  starknet-network:
