[package]
name = "mock_contracts"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
pitchlake_verifier = { path = "/home/ametel/source/pitchlake-coprocessor" }
starknet = "2.11.2"

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true
build-external-contracts = [
    "pitchlake_verifier::PitchLakeVerifier",
    "pitchlake_verifier::Risc0Groth16VerifierBN254",
    "pitchlake_verifier::UniversalECIP",
    "pitchlake_verifier::MockPitchLakeClient",
]

[scripts]
test = "snforge test"
