codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic settings
        target: auto
        threshold: 1%
        base: auto
        # advanced settings
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        # basic settings
        target: auto
        threshold: 1%
        base: auto
        # advanced settings
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches: null

ignore:
  - "tests/"
  - "**/tests/"
  - "**/*.test.rs"
  - ".coverage/**"
  - "**/.coverage/**" 