[package]
name = "sha2_input"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.0"
fp = "0.1.4"
openzeppelin_upgrades = "2.0.0"
openzeppelin_access = "2.0.0"
# fossil_store = { git = "https://github.com/OilerNetwork/fossil-light-client.git", package = "fossil_store" }

[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.12.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = [
    "snforge_std",
] # Feature name and list of other features that should be enabled with it
