[workspace]
members = ["fossil-hash-store", "pitchlake-verifier"]

[workspace.dependencies]
starknet = "2.12.1"
assert_macros = "2.12.1"
cairo_test = "2.12.1"
openzeppelin_upgrades = "2.0.0"
openzeppelin_access = "2.0.0"
snforge_std = "0.49.0"
fp = "0.1.4"

pitch_lake = { git = "https://github.com/OilerNetwork/pitchlake-monorepo.git", branch = "main" }
# pitch_lake = {git = "https://github.com/ametel01/pitchlake_starknet.git", branch = "scarb-updates"}

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true

[workspace.tool.fmt]
sort-module-level-items = true

[tool]
fmt.workspace = true

[lib]
casm = true

[cairo]
sierra-replace-ids = false
