name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
    
    - name: Install RISC Zero toolchain
      run: |
          curl -L https://risczero.com/install | bash
          export PATH="$HOME/.risc0/bin:$PATH"
          rzup install
    
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build --verbose 