name: Monorepo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Master job that depends on all others
  complete:
    name: CI Complete
    runs-on: ubuntu-latest
    needs: [ps-build, ps-test, ps-lint, op-build, op-test, op-lint]
    steps:
      - name: CI Passed
        run: echo "All CI checks have passed!"
        
  # Proving Service jobs
  ps-build:
    name: PS Build
    uses: ./.github/workflows/ps-build.yml

  ps-test:
    name: PS Test
    uses: ./.github/workflows/shared-test.yml
    with:
      component: 'ps'
    needs: [ps-build]

  ps-lint:
    name: PS Lint
    uses: ./.github/workflows/ps-lint.yml
        
  # Offchain Processor jobs
  op-build:
    name: OP Build
    uses: ./.github/workflows/op-build.yml

  op-test:
    name: OP Test
    uses: ./.github/workflows/shared-test.yml
    with:
      component: 'op'
    needs: [op-build]

  op-lint:
    name: OP Lint
    uses: ./.github/workflows/op-lint.yml 