name: Offchain Processor CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/op-lint.yml

  test:
    uses: ./.github/workflows/op-test.yml
