name: PS Test

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
          
      - name: Start PostgreSQL container
        run: cd proving-service/docker && docker-compose -f docker-compose.test.yml up -d
      
      - name: Wait for PostgreSQL to start
        run: sleep 10
          
      - name: Run tests
        run: cd proving-service && cargo test
      
      - name: Stop containers
        if: always()
        run: cd proving-service/docker && docker-compose -f docker-compose.test.yml down 