name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # This is a coordinating job that depends on the other jobs
  # It will only pass if all dependent jobs pass
  complete:
    name: CI Complete
    runs-on: ubuntu-latest
    needs: [lint, build, test]
    steps:
      - name: CI Passed
        run: echo "All CI checks have passed!"
        
  # Run the lint job defined in lint.yml
  lint:
    uses: ./.github/workflows/lint.yml
    
  # Run the build job defined in build.yml
  build:
    uses: ./.github/workflows/build.yml
    
  # Run the test job defined in test.yml
  test:
    uses: ./.github/workflows/test.yml
