name: Standard Build

on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
        description: 'Component to build (ps or op)'
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@nightly
      
      # OP-specific setup
      - name: Install OP dependencies
        if: inputs.component == 'op'
        run: sudo apt update && sudo apt install -y libomp-dev libopenblas-dev
      
      - name: Install sqlx-cli for OP
        if: inputs.component == 'op'
        run: |
          cargo install sqlx-cli
          sqlx --version
      
      - name: Check sqlx metadata for OP
        if: inputs.component == 'op'
        run: cd offchain-processor && cargo sqlx prepare --workspace --check
      
      # Build step
      - name: Build
        run: |
          if [ "${{ inputs.component }}" == "ps" ]; then
            cd proving-service && cargo build --verbose
          else
            cd offchain-processor && cargo build --verbose
          fi 